# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6DH7-hr_V8rINtOctrYWvQjB-zlR4p0
"""

pip install streamlit

import streamlit as st
import joblib
import pandas as pd
import numpy as np

# --- Configuration and Model Loading ---
st.set_page_config(
    page_title="Medical Cost Predictor",
    page_icon="🏥",
    layout="centered"
)

# Use Streamlit's caching mechanism (@st.cache_resource) to load the model only once.
@st.cache_resource
def load_pipeline():
    """Loads the trained ML pipeline (preprocessor + model)."""
    model_filename = 'medical_cost_pipeline.pkl'
    try:
        # Load the model using the updated filename
        stack = joblib.load(model_filename)
        return stack
    except FileNotFoundError:
        # Display a clear error if the model file is missing
        st.error(f"Error: Model file '{model_filename}' not found. "
                 "Please ensure the file is in the root of your GitHub repository.")
        st.stop()
    except Exception as e:
        st.error(f"Error loading model: {e}")
        st.stop()

# Load the pipeline into the variable 'stack'
stack = load_pipeline()

# --- Streamlit UI Components ---
st.title("🏥 Medical Insurance Cost Predictor")
st.markdown("Enter the patient's details below to estimate the annual medical insurance charge.")

# Create two columns for a clean layout
col1, col2 = st.columns(2)

with col1:
    # Numeric and Categorical Input 1
    age = st.slider("Age", 18, 65, 30, key='age')
    sex = st.selectbox("Sex", ['male', 'female'], key='sex')
    smoker = st.selectbox("Smoker", ['no', 'yes'], key='smoker')

with col2:
    # Numeric and Categorical Input 2
    bmi = st.number_input("BMI (e.g., 25.0)", 15.0, 55.0, 25.0, step=0.1, key='bmi')
    children = st.slider("Children", 0, 5, 0, key='children')
    region = st.selectbox("Region", ['southeast', 'southwest', 'northeast', 'northwest'], key='region')

# --- Prediction Logic ---
if st.button("Calculate Insurance Charge", key='predict_button', type="primary"):
    # 1. Gather all user inputs into a dictionary
    input_data = {
        'age': age,
        'sex': sex,
        'bmi': bmi,
        'children': children,
        'smoker': smoker,
        'region': region
    }

    # 2. Convert dictionary to a DataFrame (required by the pipeline structure)
    features_df = pd.DataFrame([input_data])

    # 3. Make the prediction using the loaded 'stack' pipeline
    with st.spinner('Calculating estimate...'):
        try:
            # The pipeline handles all necessary pre-processing and prediction
            prediction = stack.predict(features_df)[0]

            # Format the output for display
            predicted_charge = f"${prediction:,.2f}"

            # 4. Display the results
            st.success(f"### Predicted Annual Insurance Charge")
            st.info(f"The estimated cost is: **{predicted_charge}**")
            st.balloons()

        except Exception as e:
            st.error(f"An error occurred during prediction. Please check your inputs. Error details: {e}")

# --- Footer/Model Info (in sidebar) ---
st.sidebar.header("Deployment Details")
st.sidebar.markdown(
    """
    This application is powered by a machine learning pipeline, called `stack`,
    trained to predict medical costs based on demographic and lifestyle factors.
    """
)
st.sidebar.markdown("---")
st.sidebar.caption("The deployment utilizes Streamlit and a serialized model (`medical_cost_stack.pkl`).")
